// src/components/Login/Login.tsx
import { IonLoading, useIonLoading, IonCol, IonGrid, IonRow, IonCard, IonCardContent, IonCardHeader, IonCardSubtitle, IonCardTitle, IonButton, IonImg } from '@ionic/react';
import { IonInput, IonItem, IonList } from '@ionic/react';
import styles from './Login.module.scss';
import React, { useEffect, useState } from 'react'
import { login } from '../../services/auth';
import { setUser, clearUser } from '@/helpers/onboarding';
import { useHistory } from 'react-router-dom'

export const Login = () => {

    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    
    const [present, dismiss] = useIonLoading();
    const history = useHistory();

    const doLogin = async (evt: any) => {
        evt.preventDefault();

        try {
            present({
                message: 'Loading ...',
            });

            const { data } = await login({
                email,
                password,
                device: 'app'
            });

            setUser( data );            
            history.replace('/home')

        } catch(error) {

        } finally {
            dismiss();
        }
    }

    useEffect(() => {
        clearUser()
    }, [])

    return (
        <div className={styles.layout}>
            <IonGrid class={styles.gridLogin}>
                <IonRow className='ion-justify-content-center ion-align-items-center ion-margin-top'>
                    <IonCol size="11" className="ion-text-center">
                        <IonCard>
                            <IonCardHeader className={styles.bgLogin}>
                                <div className={styles.bgLoginOverlay}></div>
                                <div style={{ position: "relative" }}>
                                    <IonCardTitle class='text-white'>Welcome Back !</IonCardTitle>
                                    <IonCardSubtitle class='text-white-50'>Sign in to continue.</IonCardSubtitle>
                                    <IonImg src='/assets/images/logo-sm-dark.png' style={{height:"70px"}}></IonImg>
                                </div>
                            </IonCardHeader>

                            <IonCardContent>
                                <IonList>
                                    <IonItem>
                                        <IonInput label="Email" type="email" labelPlacement="stacked" placeholder="Enter Email"
                                            onIonInput={(evt: any) => setEmail(evt.target.value)}
                                        ></IonInput>
                                    </IonItem>
                                    <IonItem>
                                        <IonInput label="Password" type="password" labelPlacement="stacked" placeholder="Enter password"
                                            onIonInput={(evt: any) => setPassword(evt.target.value)}
                                        ></IonInput>
                                    </IonItem>
                                </IonList>
                                    <IonButton type='button' className='ion-margin-top' expand="block" onClick={(evt) => doLogin(evt)}> Log In </IonButton>

                                    <IonLoading trigger="open-loading" message="Dismissing after 3 seconds..." duration={3000} />

                            </IonCardContent>
                        </IonCard>
                    </IonCol>
                </IonRow>
            </IonGrid>
        </div>
    )
}

// src/views/login.vue
<template>
    <div class="row main-content mt-5 justify-content-center">
        <div class="col-md-8 col-lg-6 col-xl-4">
            <div class="card overflow-hidden">
                <div class="bg-login text-center">
                    <div class="bg-login-overlay"></div>

                    <div class="position-relative">
                        <h5 class="text-white font-size-20">Welcome Back !</h5>
                        <p class="text-white-50 mb-0">Sign in to continue.</p>
                        <a href="/" class="logo logo-admin mt-4">
                            <img src="/assets/images/logo-sm-dark.png" alt="" height="30">
                        </a>
                    </div>
                </div>
                <div class="card-body pt-5">
                    <div class="p-2">
                        <form class="form-horizontal" method="post" @submit="onSubmit($event)">
                            
                            <div class="alert alert-danger alert-dismissible fade show" role="alert" v-if="error">
                                {{ error }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>

                            <div class="mb-3">
                                <label class="form-label" for="username">Email</label>
                                <input type="email" class="form-control" id="username" placeholder="Enter email" name="email" v-model="form.email">
                            </div>

                            <div class="mb-3">
                                <label class="form-label" for="userpassword">Password</label>
                                <input type="password" class="form-control" id="userpassword" name="password"  v-model="form.password"
                                placeholder="Enter password">
                            </div>

                            <div class="mt-3">
                                <button class="btn btn-primary w-100 waves-effect waves-light" type="submit">Log In </button>
                            </div>
                        
                        </form>
                    </div>

                </div>
            </div>
            <div class="mt-5 text-center">
                <p>©
                    {{ date }} Qovex. 
                </p>
            </div>

        </div>
    </div>
</template>

<script setup>
import { useRoute, useRouter } from 'vue-router'
import { ref, watch, reactive } from 'vue'
import {login}  from '@/services/auth';
import {setUser} from '@/helpers/onboarding'

const date = ref( new Date().getFullYear() );
const error = ref('');
const router = useRouter();

const initialState = {
    email: '',
    password: '',
    device: 'web'
};

const form = reactive({...initialState})

const onSubmit = async ( evt ) => {
    evt.preventDefault();
    try {
        const {data} = await login( form );
        setUser( data )
        router.push('/')
    } catch (err){
        error.value = err.message;
    }
}

</script>
<style>
    
</style>
